config/routes.rb
Rails.application.routes.draw do
  

  resources :ejercicios
  resources :temas
  devise_for :users
  resources :posts

  resources :materia
  root 'welcome#index'

  mathjax 'mathjax'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tema.rb
class Tema < ApplicationRecord
  belongs_to :materium_id
  has_one :post_id
end

app/controllers/temas_controller.rb
class TemasController < ApplicationController
  before_action :set_tema, only: [:show, :edit, :update, :destroy]

  # GET /temas
  # GET /temas.json
  def index
    @temas = Tema.all
  end

  # GET /temas/1
  # GET /temas/1.json
  def show
  end

  # GET /temas/new
  def new
    @tema = Tema.new
  end

  # GET /temas/1/edit
  def edit
  end

  # POST /temas
  # POST /temas.json
  def create
    @tema = Tema.new(tema_params)

    respond_to do |format|
      if @tema.save
        format.html { redirect_to @tema, notice: 'Tema was successfully created.' }
        format.json { render :show, status: :created, location: @tema }
      else
        format.html { render :new }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temas/1
  # PATCH/PUT /temas/1.json
  def update
    respond_to do |format|
      if @tema.update(tema_params)
        format.html { redirect_to @tema, notice: 'Tema was successfully updated.' }
        format.json { render :show, status: :ok, location: @tema }
      else
        format.html { render :edit }
        format.json { render json: @tema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temas/1
  # DELETE /temas/1.json
  def destroy
    @tema.destroy
    respond_to do |format|
      format.html { redirect_to temas_url, notice: 'Tema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tema
      @tema = Tema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tema_params
      params.require(:tema).permit(:materium_id_id, :post_id_id, :evaluacion, :titulo)
    end
end

app/helpers/temas_helper.rb
module TemasHelper
end

app/views/temas/_form.html.erb
<%= form_with(model: tema, local: true) do |form| %>
  <% if tema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tema.errors.count, "error") %> prohibited this tema from being saved:</h2>

      <ul>
      <% tema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :materium_id_id %>
    <%= form.text_field :materium_id_id, id: :tema_materium_id_id %>
  </div>

  <div class="field">
    <%= form.label :post_id_id %>
    <%= form.text_field :post_id_id, id: :tema_post_id_id %>
  </div>

  <div class="field">
    <%= form.label :evaluacion %>
    <%= form.text_area :evaluacion, id: :tema_evaluacion %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :tema_titulo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/temas/edit.html.erb
<h1>Editing Tema</h1>

<%= render 'form', tema: @tema %>

<%= link_to 'Show', @tema %> |
<%= link_to 'Back', temas_path %>

app/views/temas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temas</h1>

<table>
  <thead>
    <tr>
      <th>Materium</th>
      <th>Post</th>
      <th>Evaluacion</th>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temas.each do |tema| %>
      <tr>
        <td><%= tema.materium_id %></td>
        <td><%= tema.post_id %></td>
        <td><%= tema.evaluacion %></td>
        <td><%= tema.titulo %></td>
        <td><%= link_to 'Show', tema %></td>
        <td><%= link_to 'Edit', edit_tema_path(tema) %></td>
        <td><%= link_to 'Destroy', tema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tema', new_tema_path %>

app/views/temas/new.html.erb
<h1>New Tema</h1>

<%= render 'form', tema: @tema %>

<%= link_to 'Back', temas_path %>

app/views/temas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Materium:</strong>
  <%= @tema.materium_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @tema.post_id %>
</p>

<p>
  <strong>Evaluacion:</strong>
  <%= @tema.evaluacion %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @tema.titulo %>
</p>

<%= link_to 'Edit', edit_tema_path(@tema) %> |
<%= link_to 'Back', temas_path %>