config/routes.rb
Rails.application.routes.draw do
  

  resources :ejercicios
  resources :temas
  devise_for :users
  resources :posts

  resources :materia
  root 'welcome#index'

  mathjax 'mathjax'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ejercicio.rb
class Ejercicio < ApplicationRecord
  belongs_to :tema_id
end

app/controllers/ejercicios_controller.rb
class EjerciciosController < ApplicationController
  before_action :set_ejercicio, only: [:show, :edit, :update, :destroy]

  # GET /ejercicios
  # GET /ejercicios.json
  def index
    @ejercicios = Ejercicio.all
  end

  # GET /ejercicios/1
  # GET /ejercicios/1.json
  def show
  end

  # GET /ejercicios/new
  def new
    @ejercicio = Ejercicio.new
  end

  # GET /ejercicios/1/edit
  def edit
  end

  # POST /ejercicios
  # POST /ejercicios.json
  def create
    @ejercicio = Ejercicio.new(ejercicio_params)

    respond_to do |format|
      if @ejercicio.save
        format.html { redirect_to @ejercicio, notice: 'Ejercicio was successfully created.' }
        format.json { render :show, status: :created, location: @ejercicio }
      else
        format.html { render :new }
        format.json { render json: @ejercicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ejercicios/1
  # PATCH/PUT /ejercicios/1.json
  def update
    respond_to do |format|
      if @ejercicio.update(ejercicio_params)
        format.html { redirect_to @ejercicio, notice: 'Ejercicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @ejercicio }
      else
        format.html { render :edit }
        format.json { render json: @ejercicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ejercicios/1
  # DELETE /ejercicios/1.json
  def destroy
    @ejercicio.destroy
    respond_to do |format|
      format.html { redirect_to ejercicios_url, notice: 'Ejercicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ejercicio
      @ejercicio = Ejercicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ejercicio_params
      params.require(:ejercicio).permit(:tema_id_id, :consigna, :respuesta)
    end
end

app/helpers/ejercicios_helper.rb
module EjerciciosHelper
end

app/views/ejercicios/_form.html.erb
<%= form_with(model: ejercicio, local: true) do |form| %>
  <% if ejercicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ejercicio.errors.count, "error") %> prohibited this ejercicio from being saved:</h2>

      <ul>
      <% ejercicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tema_id_id %>
    <%= form.text_field :tema_id_id, id: :ejercicio_tema_id_id %>
  </div>

  <div class="field">
    <%= form.label :consigna %>
    <%= form.text_area :consigna, id: :ejercicio_consigna %>
  </div>

  <div class="field">
    <%= form.label :respuesta %>
    <%= form.text_field :respuesta, id: :ejercicio_respuesta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ejercicios/edit.html.erb
<h1>Editing Ejercicio</h1>

<%= render 'form', ejercicio: @ejercicio %>

<%= link_to 'Show', @ejercicio %> |
<%= link_to 'Back', ejercicios_path %>

app/views/ejercicios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ejercicios</h1>

<table>
  <thead>
    <tr>
      <th>Tema</th>
      <th>Consigna</th>
      <th>Respuesta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ejercicios.each do |ejercicio| %>
      <tr>
        <td><%= ejercicio.tema_id %></td>
        <td><%= ejercicio.consigna %></td>
        <td><%= ejercicio.respuesta %></td>
        <td><%= link_to 'Show', ejercicio %></td>
        <td><%= link_to 'Edit', edit_ejercicio_path(ejercicio) %></td>
        <td><%= link_to 'Destroy', ejercicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ejercicio', new_ejercicio_path %>

app/views/ejercicios/new.html.erb
<h1>New Ejercicio</h1>

<%= render 'form', ejercicio: @ejercicio %>

<%= link_to 'Back', ejercicios_path %>

app/views/ejercicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tema:</strong>
  <%= @ejercicio.tema_id %>
</p>

<p>
  <strong>Consigna:</strong>
  <%= @ejercicio.consigna %>
</p>

<p>
  <strong>Respuesta:</strong>
  <%= @ejercicio.respuesta %>
</p>

<%= link_to 'Edit', edit_ejercicio_path(@ejercicio) %> |
<%= link_to 'Back', ejercicios_path %>