config/routes.rb
Rails.application.routes.draw do
  

  resources :ejercicios
  resources :temas
  devise_for :users
  resources :posts

  resources :materia
  root 'welcome#index'

  mathjax 'mathjax'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :portada, :styles => { :medium => "600x600>", :thumb => "200x200>" }, :default_url => "/images/:style/nocover.png"
  validates_attachment_content_type :portada, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authenticate_admin!, only: [:new, :create, :destroy, :update, :edit]  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  #   require 'mathematical'
  #   require 'math-to-itex'

    # Convertir ecuaciones LaTeX en imágenes
  #  @contenidoeq = MathToItex(@post.contenido).convert do |eq, type|
  #    svg_content = Mathematical.new(:base64 => true).render(eq)
  #    con=svg_content[:data]
      # Crear tags para imagen con codificación base64
  #    %|<img class="#{type.to_s}-math" data-math-type="#{type.to_s}-math" src="#{con}"/>|
  #  end

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end
  def mercury_update
  page = Page.find(params[:id])
  page.name = params[:content][:page_name][:value]
  page.content = params[:content][:page_content][:value]
  page.save!
  render text: ""
end
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def authenticate_admin!
      if current_user.privilegios < 10
        redirect_to posts_path, notice: "No estás autorizado a acceder a esta sección" #, status: :unauthorized
      end     
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :autor, :tags, :materia_id, :descripcion, :orden, :tiempo, :contenido, :bibliografia, :portada)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/Chindex.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Tags</th>
      <th>Materia</th>
      <th>Descripcion</th>
      <th>Orden</th>
      <th>Tiempo</th>
      <th>Contenido</th>
      <th>Bibliografia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.autor %></td>
        <td><%= post.tags %></td>
        <td><%= post.materia_id %></td>
        <td><%= post.descripcion %></td>
        <td><%= post.orden %></td>
        <td><%= post.tiempo %></td>
        <td><%= post.contenido %></td>
        <td><%= post.bibliografia %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/Chow.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @post.autor %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @post.tags %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @post.materia_id %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @post.descripcion %>
</p>

<p>
  <strong>Orden:</strong>
  <%= @post.orden %>
</p>

<p>
  <strong>Tiempo:</strong>
  <%= @post.tiempo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.contenido %>
</p>

<p>
  <strong>Bibliografia:</strong>
  <%= @post.bibliografia %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, multipart: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :post_titulo %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor, id: :post_autor %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, id: :post_tags %>
  </div>

  <div class="field">
    <%= form.label :materia_id %>
    <%= form.text_field :materia_id, id: :post_materia_id %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :post_descripcion %>
  </div>

  <div class="field">
    <%= form.label :orden %>
    <%= form.number_field :orden, id: :post_orden %>
  </div>

  <div class="field">
    <%= form.label :tiempo %>
    <%= form.number_field :tiempo, id: :post_tiempo %>
  </div>

  <div class="field">
    
    <%= form.text_area :contenido, id: :post_contenido %>
    <script type="text/javascript">
      $('#post_contenido').aloha();

    </script>
    <%= form.file_field :portada %>
  </div>

  <div class="field">
    <%= form.label :bibliografia %>
    <%= form.text_field :bibliografia, id: :post_bibliografia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.haml
.container.marco
  .row.center
    %h3 Publicaciones
    .chip Todo
  .row
    -@posts.each do |post|

      .col.s12.m4
        .card.hoverable
          .card-image
            = image_tag post.portada.url(:thumb)
            %h5
              = post.titulo
            %br
            %small
              %i.tiny.material-icons face
              = post.autor
          .card-stacked
            .card-content
              = post.descripcion
            .card-action
              = link_to 'Leer', post

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.haml
:javascript
  $(document).ready(function(){
    $('.materialboxed').materialbox();
  })
.container
  .card.marco
    %h3.center
      = @post.titulo
    .divider
    .datapub
      %i.material-icons face
      = @post.autor
      |
      %i.material-icons date_range
      = @post.created_at.to_date
      |
      %i.material-icons assignment
      = @post.materia_id
      |
    .divider
    = image_tag @post.portada(:original), :class => "materialboxed", :width => 300
    =raw @post.contenido
    
    %ul{:class=>"collapsible", "data-collapsible"=>"accordion"}
      %li
        .collapsible-header
          %i.material-icons local_library
          Bibliografía
        .collapsible-body
          = raw @post.bibliografia
      %li
        .collapsible-header
          %i.material-icons bookmark
          Etiquetas
        .collapsible-body
          = @post.tags