config/routes.rb
Rails.application.routes.draw do
  

  resources :ejercicios
  resources :temas
  devise_for :users
  resources :posts

  resources :materia
  root 'welcome#index'

  mathjax 'mathjax'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.haml
%html
  %head
    %title Ludere
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel =>"stylesheet"}

    = mathjax_tag
  %body.grey.lighten-4
    %nav.inverse
      .container.nav-wrapper
        %a{:href=> "/", :class=>"brand-logo"}
          %i.material-icons play_arrow
          .logo Ludere
        %a{:href=> "#!", :class=>"button-collapse", "data-activates"=>"mobile-demo"}
          %i.material-icons menu

        %ul.right.hide-on-med-and-down
          %li
            =link_to("Aprender", materia_path)
          /  %li
          /    %a{:href=> "#!"} Apps
          %li
            =link_to("Publicaciones", posts_path)
          -if user_signed_in?
            %li
              =link_to raw('<i class="material-icons">clear</i>'), destroy_user_session_path, method: :delete, :class => "tooltipped", "data-tooltip" => "Cerrar sesión"
          -else
            %li
              =link_to "Crear cuenta", new_user_registration_path
            %li
              =link_to "Iniciar sesión", user_session_path
          

        %ul{:class=>"side-nav", :id=>"mobile-demo"}
          %li
            =link_to("Aprender", materia_path)
          /  %li
          /    %a{:href=> "#!"} Apps
          %li
            =link_to("Publicaciones", posts_path)
          
          -if user_signed_in?
            / Perfil
            / Logros
            %li
              =link_to raw('<i class="material-icons">clear</i> Cerrar sesión'), destroy_user_session_path, method: :delete, :class => "tooltipped", "data-tooltip" => "Cerrar sesión"
          -else
            %li
              =link_to "Crear cuenta", new_user_registration_path
            %li
              =link_to "Iniciar sesión", user_session_path
        :javascript
          $(".button-collapse").sideNav();
    
    = yield
    %footer.page-footer
      .container
        .row
          .col.s6
            %ul
              %li Nuestro equipo
              %li ¡Quiero colaborar!
          .col.s6
            %ul.right
              %li Términos y condiciones
              %li Privacidad
              %li Redes sociales
      .footer-copyright
        .container.center
          Ludere
          %i.tiny.material-icons copyright
          |
          %a{:rel=>"license", :href=>"http://creativecommons.org/licenses/by/4.0/"}
            %img{:alt=>"Creative Commons License", :style=>"border-width:0", :src=>"https://i.creativecommons.org/l/by/4.0/80x15.png"}